// Copyright (c) 2024 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.9
// source: assignment_function.proto

package assignmentFunction

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChallengeRotation int32

const (
	ChallengeRotation_DAILY   ChallengeRotation = 0
	ChallengeRotation_WEEKLY  ChallengeRotation = 1
	ChallengeRotation_MONTHLY ChallengeRotation = 2
	ChallengeRotation_NONE    ChallengeRotation = 3
)

// Enum value maps for ChallengeRotation.
var (
	ChallengeRotation_name = map[int32]string{
		0: "DAILY",
		1: "WEEKLY",
		2: "MONTHLY",
		3: "NONE",
	}
	ChallengeRotation_value = map[string]int32{
		"DAILY":   0,
		"WEEKLY":  1,
		"MONTHLY": 2,
		"NONE":    3,
	}
)

func (x ChallengeRotation) Enum() *ChallengeRotation {
	p := new(ChallengeRotation)
	*p = x
	return p
}

func (x ChallengeRotation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChallengeRotation) Descriptor() protoreflect.EnumDescriptor {
	return file_assignment_function_proto_enumTypes[0].Descriptor()
}

func (ChallengeRotation) Type() protoreflect.EnumType {
	return &file_assignment_function_proto_enumTypes[0]
}

func (x ChallengeRotation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChallengeRotation.Descriptor instead.
func (ChallengeRotation) EnumDescriptor() ([]byte, []int) {
	return file_assignment_function_proto_rawDescGZIP(), []int{0}
}

type AssignmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Goals         []*Goal                `protobuf:"bytes,3,rep,name=goals,proto3" json:"goals,omitempty"`
	Challenge     *Challenge             `protobuf:"bytes,4,opt,name=challenge,proto3" json:"challenge,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignmentRequest) Reset() {
	*x = AssignmentRequest{}
	mi := &file_assignment_function_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignmentRequest) ProtoMessage() {}

func (x *AssignmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_function_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignmentRequest.ProtoReflect.Descriptor instead.
func (*AssignmentRequest) Descriptor() ([]byte, []int) {
	return file_assignment_function_proto_rawDescGZIP(), []int{0}
}

func (x *AssignmentRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *AssignmentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AssignmentRequest) GetGoals() []*Goal {
	if x != nil {
		return x.Goals
	}
	return nil
}

func (x *AssignmentRequest) GetChallenge() *Challenge {
	if x != nil {
		return x.Challenge
	}
	return nil
}

type AssignmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	AssignedGoals []*Goal                `protobuf:"bytes,3,rep,name=assignedGoals,proto3" json:"assignedGoals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignmentResponse) Reset() {
	*x = AssignmentResponse{}
	mi := &file_assignment_function_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignmentResponse) ProtoMessage() {}

func (x *AssignmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_function_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignmentResponse.ProtoReflect.Descriptor instead.
func (*AssignmentResponse) Descriptor() ([]byte, []int) {
	return file_assignment_function_proto_rawDescGZIP(), []int{1}
}

func (x *AssignmentResponse) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *AssignmentResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AssignmentResponse) GetAssignedGoals() []*Goal {
	if x != nil {
		return x.AssignedGoals
	}
	return nil
}

type Challenge struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Code                   string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name                   string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	StartDate              *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=startDate,proto3" json:"startDate,omitempty"`
	EndDate                *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=endDate,proto3" json:"endDate,omitempty"`
	EndAfter               int32                  `protobuf:"varint,5,opt,name=endAfter,proto3" json:"endAfter,omitempty"`
	RepeatAfter            int32                  `protobuf:"varint,6,opt,name=repeatAfter,proto3" json:"repeatAfter,omitempty"`
	Rotation               ChallengeRotation      `protobuf:"varint,7,opt,name=rotation,proto3,enum=accelbyte.challenge.assignmentFunction.ChallengeRotation" json:"rotation,omitempty"`
	ActiveGoalsPerRotation int32                  `protobuf:"varint,8,opt,name=activeGoalsPerRotation,proto3" json:"activeGoalsPerRotation,omitempty"`
	ResetConfig            *ResetConfig           `protobuf:"bytes,9,opt,name=resetConfig,proto3" json:"resetConfig,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Challenge) Reset() {
	*x = Challenge{}
	mi := &file_assignment_function_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Challenge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Challenge) ProtoMessage() {}

func (x *Challenge) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_function_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Challenge.ProtoReflect.Descriptor instead.
func (*Challenge) Descriptor() ([]byte, []int) {
	return file_assignment_function_proto_rawDescGZIP(), []int{2}
}

func (x *Challenge) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Challenge) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Challenge) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *Challenge) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

func (x *Challenge) GetEndAfter() int32 {
	if x != nil {
		return x.EndAfter
	}
	return 0
}

func (x *Challenge) GetRepeatAfter() int32 {
	if x != nil {
		return x.RepeatAfter
	}
	return 0
}

func (x *Challenge) GetRotation() ChallengeRotation {
	if x != nil {
		return x.Rotation
	}
	return ChallengeRotation_DAILY
}

func (x *Challenge) GetActiveGoalsPerRotation() int32 {
	if x != nil {
		return x.ActiveGoalsPerRotation
	}
	return 0
}

func (x *Challenge) GetResetConfig() *ResetConfig {
	if x != nil {
		return x.ResetConfig
	}
	return nil
}

type ResetConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResetTime     string                 `protobuf:"bytes,1,opt,name=resetTime,proto3" json:"resetTime,omitempty"`
	ResetDay      int32                  `protobuf:"varint,2,opt,name=resetDay,proto3" json:"resetDay,omitempty"`
	ResetDate     int32                  `protobuf:"varint,3,opt,name=resetDate,proto3" json:"resetDate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetConfig) Reset() {
	*x = ResetConfig{}
	mi := &file_assignment_function_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetConfig) ProtoMessage() {}

func (x *ResetConfig) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_function_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetConfig.ProtoReflect.Descriptor instead.
func (*ResetConfig) Descriptor() ([]byte, []int) {
	return file_assignment_function_proto_rawDescGZIP(), []int{3}
}

func (x *ResetConfig) GetResetTime() string {
	if x != nil {
		return x.ResetTime
	}
	return ""
}

func (x *ResetConfig) GetResetDay() int32 {
	if x != nil {
		return x.ResetDay
	}
	return 0
}

func (x *ResetConfig) GetResetDate() int32 {
	if x != nil {
		return x.ResetDate
	}
	return 0
}

type Goal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	ChallengeCode string                 `protobuf:"bytes,2,opt,name=challengeCode,proto3" json:"challengeCode,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	IsActive      bool                   `protobuf:"varint,4,opt,name=isActive,proto3" json:"isActive,omitempty"`
	Tags          []*Tag                 `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	Requirements  []*Requirement         `protobuf:"bytes,6,rep,name=requirements,proto3" json:"requirements,omitempty"`
	Rewards       []*Reward              `protobuf:"bytes,7,rep,name=rewards,proto3" json:"rewards,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Goal) Reset() {
	*x = Goal{}
	mi := &file_assignment_function_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Goal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Goal) ProtoMessage() {}

func (x *Goal) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_function_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Goal.ProtoReflect.Descriptor instead.
func (*Goal) Descriptor() ([]byte, []int) {
	return file_assignment_function_proto_rawDescGZIP(), []int{4}
}

func (x *Goal) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Goal) GetChallengeCode() string {
	if x != nil {
		return x.ChallengeCode
	}
	return ""
}

func (x *Goal) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Goal) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Goal) GetTags() []*Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Goal) GetRequirements() []*Requirement {
	if x != nil {
		return x.Requirements
	}
	return nil
}

func (x *Goal) GetRewards() []*Reward {
	if x != nil {
		return x.Rewards
	}
	return nil
}

func (x *Goal) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Goal) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Requirement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operator      string                 `protobuf:"bytes,1,opt,name=operator,proto3" json:"operator,omitempty"`
	Predicates    []*Predicate           `protobuf:"bytes,2,rep,name=predicates,proto3" json:"predicates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Requirement) Reset() {
	*x = Requirement{}
	mi := &file_assignment_function_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Requirement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Requirement) ProtoMessage() {}

func (x *Requirement) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_function_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Requirement.ProtoReflect.Descriptor instead.
func (*Requirement) Descriptor() ([]byte, []int) {
	return file_assignment_function_proto_rawDescGZIP(), []int{5}
}

func (x *Requirement) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *Requirement) GetPredicates() []*Predicate {
	if x != nil {
		return x.Predicates
	}
	return nil
}

type Predicate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParameterName string                 `protobuf:"bytes,1,opt,name=parameterName,proto3" json:"parameterName,omitempty"`
	ParameterType string                 `protobuf:"bytes,2,opt,name=parameterType,proto3" json:"parameterType,omitempty"`
	Matcher       string                 `protobuf:"bytes,3,opt,name=matcher,proto3" json:"matcher,omitempty"`
	TargetValue   float32                `protobuf:"fixed32,4,opt,name=targetValue,proto3" json:"targetValue,omitempty"`
	StatCycleId   *string                `protobuf:"bytes,5,opt,name=statCycleId,proto3,oneof" json:"statCycleId,omitempty"`
	Id            string                 `protobuf:"bytes,6,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Predicate) Reset() {
	*x = Predicate{}
	mi := &file_assignment_function_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Predicate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Predicate) ProtoMessage() {}

func (x *Predicate) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_function_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Predicate.ProtoReflect.Descriptor instead.
func (*Predicate) Descriptor() ([]byte, []int) {
	return file_assignment_function_proto_rawDescGZIP(), []int{6}
}

func (x *Predicate) GetParameterName() string {
	if x != nil {
		return x.ParameterName
	}
	return ""
}

func (x *Predicate) GetParameterType() string {
	if x != nil {
		return x.ParameterType
	}
	return ""
}

func (x *Predicate) GetMatcher() string {
	if x != nil {
		return x.Matcher
	}
	return ""
}

func (x *Predicate) GetTargetValue() float32 {
	if x != nil {
		return x.TargetValue
	}
	return 0
}

func (x *Predicate) GetStatCycleId() string {
	if x != nil && x.StatCycleId != nil {
		return *x.StatCycleId
	}
	return ""
}

func (x *Predicate) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Reward struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	ItemId        string                 `protobuf:"bytes,2,opt,name=itemId,proto3" json:"itemId,omitempty"`
	ItemName      string                 `protobuf:"bytes,3,opt,name=itemName,proto3" json:"itemName,omitempty"`
	Quantity      float32                `protobuf:"fixed32,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reward) Reset() {
	*x = Reward{}
	mi := &file_assignment_function_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reward) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reward) ProtoMessage() {}

func (x *Reward) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_function_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reward.ProtoReflect.Descriptor instead.
func (*Reward) Descriptor() ([]byte, []int) {
	return file_assignment_function_proto_rawDescGZIP(), []int{7}
}

func (x *Reward) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Reward) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *Reward) GetItemName() string {
	if x != nil {
		return x.ItemName
	}
	return ""
}

func (x *Reward) GetQuantity() float32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type Goals struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Goals         []*Goal                `protobuf:"bytes,1,rep,name=goals,proto3" json:"goals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Goals) Reset() {
	*x = Goals{}
	mi := &file_assignment_function_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Goals) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Goals) ProtoMessage() {}

func (x *Goals) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_function_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Goals.ProtoReflect.Descriptor instead.
func (*Goals) Descriptor() ([]byte, []int) {
	return file_assignment_function_proto_rawDescGZIP(), []int{8}
}

func (x *Goals) GetGoals() []*Goal {
	if x != nil {
		return x.Goals
	}
	return nil
}

type Tag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tag) Reset() {
	*x = Tag{}
	mi := &file_assignment_function_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tag) ProtoMessage() {}

func (x *Tag) ProtoReflect() protoreflect.Message {
	mi := &file_assignment_function_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tag.ProtoReflect.Descriptor instead.
func (*Tag) Descriptor() ([]byte, []int) {
	return file_assignment_function_proto_rawDescGZIP(), []int{9}
}

func (x *Tag) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_assignment_function_proto protoreflect.FileDescriptor

const file_assignment_function_proto_rawDesc = "" +
	"\n" +
	"\x19assignment_function.proto\x12&accelbyte.challenge.assignmentFunction\x1a\x1fgoogle/protobuf/timestamp.proto\"\xde\x01\n" +
	"\x11AssignmentRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\tR\x06userId\x12B\n" +
	"\x05goals\x18\x03 \x03(\v2,.accelbyte.challenge.assignmentFunction.GoalR\x05goals\x12O\n" +
	"\tchallenge\x18\x04 \x01(\v21.accelbyte.challenge.assignmentFunction.ChallengeR\tchallenge\"\x9e\x01\n" +
	"\x12AssignmentResponse\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\tR\x06userId\x12R\n" +
	"\rassignedGoals\x18\x03 \x03(\v2,.accelbyte.challenge.assignmentFunction.GoalR\rassignedGoals\"\xc7\x03\n" +
	"\tChallenge\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x128\n" +
	"\tstartDate\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x124\n" +
	"\aendDate\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\x12\x1a\n" +
	"\bendAfter\x18\x05 \x01(\x05R\bendAfter\x12 \n" +
	"\vrepeatAfter\x18\x06 \x01(\x05R\vrepeatAfter\x12U\n" +
	"\brotation\x18\a \x01(\x0e29.accelbyte.challenge.assignmentFunction.ChallengeRotationR\brotation\x126\n" +
	"\x16activeGoalsPerRotation\x18\b \x01(\x05R\x16activeGoalsPerRotation\x12U\n" +
	"\vresetConfig\x18\t \x01(\v23.accelbyte.challenge.assignmentFunction.ResetConfigR\vresetConfig\"e\n" +
	"\vResetConfig\x12\x1c\n" +
	"\tresetTime\x18\x01 \x01(\tR\tresetTime\x12\x1a\n" +
	"\bresetDay\x18\x02 \x01(\x05R\bresetDay\x12\x1c\n" +
	"\tresetDate\x18\x03 \x01(\x05R\tresetDate\"\xc8\x03\n" +
	"\x04Goal\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12$\n" +
	"\rchallengeCode\x18\x02 \x01(\tR\rchallengeCode\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1a\n" +
	"\bisActive\x18\x04 \x01(\bR\bisActive\x12?\n" +
	"\x04tags\x18\x05 \x03(\v2+.accelbyte.challenge.assignmentFunction.TagR\x04tags\x12W\n" +
	"\frequirements\x18\x06 \x03(\v23.accelbyte.challenge.assignmentFunction.RequirementR\frequirements\x12H\n" +
	"\arewards\x18\a \x03(\v2..accelbyte.challenge.assignmentFunction.RewardR\arewards\x128\n" +
	"\tcreatedAt\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x128\n" +
	"\tupdatedAt\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"|\n" +
	"\vRequirement\x12\x1a\n" +
	"\boperator\x18\x01 \x01(\tR\boperator\x12Q\n" +
	"\n" +
	"predicates\x18\x02 \x03(\v21.accelbyte.challenge.assignmentFunction.PredicateR\n" +
	"predicates\"\xda\x01\n" +
	"\tPredicate\x12$\n" +
	"\rparameterName\x18\x01 \x01(\tR\rparameterName\x12$\n" +
	"\rparameterType\x18\x02 \x01(\tR\rparameterType\x12\x18\n" +
	"\amatcher\x18\x03 \x01(\tR\amatcher\x12 \n" +
	"\vtargetValue\x18\x04 \x01(\x02R\vtargetValue\x12%\n" +
	"\vstatCycleId\x18\x05 \x01(\tH\x00R\vstatCycleId\x88\x01\x01\x12\x0e\n" +
	"\x02id\x18\x06 \x01(\tR\x02idB\x0e\n" +
	"\f_statCycleId\"l\n" +
	"\x06Reward\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x16\n" +
	"\x06itemId\x18\x02 \x01(\tR\x06itemId\x12\x1a\n" +
	"\bitemName\x18\x03 \x01(\tR\bitemName\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x02R\bquantity\"K\n" +
	"\x05Goals\x12B\n" +
	"\x05goals\x18\x01 \x03(\v2,.accelbyte.challenge.assignmentFunction.GoalR\x05goals\"\x19\n" +
	"\x03Tag\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name*A\n" +
	"\x11ChallengeRotation\x12\t\n" +
	"\x05DAILY\x10\x00\x12\n" +
	"\n" +
	"\x06WEEKLY\x10\x01\x12\v\n" +
	"\aMONTHLY\x10\x02\x12\b\n" +
	"\x04NONE\x10\x032\x98\x01\n" +
	"\x12AssignmentFunction\x12\x81\x01\n" +
	"\x06Assign\x129.accelbyte.challenge.assignmentFunction.AssignmentRequest\x1a:.accelbyte.challenge.assignmentFunction.AssignmentResponse\"\x00B\x83\x01\n" +
	"*net.accelbyte.challenge.assignmentFunctionP\x01Z*accelbyte.net/challenge/assignmentFunction\xaa\x02&AccelByte.Challenge.AssignmentFunctionb\x06proto3"

var (
	file_assignment_function_proto_rawDescOnce sync.Once
	file_assignment_function_proto_rawDescData []byte
)

func file_assignment_function_proto_rawDescGZIP() []byte {
	file_assignment_function_proto_rawDescOnce.Do(func() {
		file_assignment_function_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_assignment_function_proto_rawDesc), len(file_assignment_function_proto_rawDesc)))
	})
	return file_assignment_function_proto_rawDescData
}

var file_assignment_function_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_assignment_function_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_assignment_function_proto_goTypes = []any{
	(ChallengeRotation)(0),        // 0: accelbyte.challenge.assignmentFunction.ChallengeRotation
	(*AssignmentRequest)(nil),     // 1: accelbyte.challenge.assignmentFunction.AssignmentRequest
	(*AssignmentResponse)(nil),    // 2: accelbyte.challenge.assignmentFunction.AssignmentResponse
	(*Challenge)(nil),             // 3: accelbyte.challenge.assignmentFunction.Challenge
	(*ResetConfig)(nil),           // 4: accelbyte.challenge.assignmentFunction.ResetConfig
	(*Goal)(nil),                  // 5: accelbyte.challenge.assignmentFunction.Goal
	(*Requirement)(nil),           // 6: accelbyte.challenge.assignmentFunction.Requirement
	(*Predicate)(nil),             // 7: accelbyte.challenge.assignmentFunction.Predicate
	(*Reward)(nil),                // 8: accelbyte.challenge.assignmentFunction.Reward
	(*Goals)(nil),                 // 9: accelbyte.challenge.assignmentFunction.Goals
	(*Tag)(nil),                   // 10: accelbyte.challenge.assignmentFunction.Tag
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
}
var file_assignment_function_proto_depIdxs = []int32{
	5,  // 0: accelbyte.challenge.assignmentFunction.AssignmentRequest.goals:type_name -> accelbyte.challenge.assignmentFunction.Goal
	3,  // 1: accelbyte.challenge.assignmentFunction.AssignmentRequest.challenge:type_name -> accelbyte.challenge.assignmentFunction.Challenge
	5,  // 2: accelbyte.challenge.assignmentFunction.AssignmentResponse.assignedGoals:type_name -> accelbyte.challenge.assignmentFunction.Goal
	11, // 3: accelbyte.challenge.assignmentFunction.Challenge.startDate:type_name -> google.protobuf.Timestamp
	11, // 4: accelbyte.challenge.assignmentFunction.Challenge.endDate:type_name -> google.protobuf.Timestamp
	0,  // 5: accelbyte.challenge.assignmentFunction.Challenge.rotation:type_name -> accelbyte.challenge.assignmentFunction.ChallengeRotation
	4,  // 6: accelbyte.challenge.assignmentFunction.Challenge.resetConfig:type_name -> accelbyte.challenge.assignmentFunction.ResetConfig
	10, // 7: accelbyte.challenge.assignmentFunction.Goal.tags:type_name -> accelbyte.challenge.assignmentFunction.Tag
	6,  // 8: accelbyte.challenge.assignmentFunction.Goal.requirements:type_name -> accelbyte.challenge.assignmentFunction.Requirement
	8,  // 9: accelbyte.challenge.assignmentFunction.Goal.rewards:type_name -> accelbyte.challenge.assignmentFunction.Reward
	11, // 10: accelbyte.challenge.assignmentFunction.Goal.createdAt:type_name -> google.protobuf.Timestamp
	11, // 11: accelbyte.challenge.assignmentFunction.Goal.updatedAt:type_name -> google.protobuf.Timestamp
	7,  // 12: accelbyte.challenge.assignmentFunction.Requirement.predicates:type_name -> accelbyte.challenge.assignmentFunction.Predicate
	5,  // 13: accelbyte.challenge.assignmentFunction.Goals.goals:type_name -> accelbyte.challenge.assignmentFunction.Goal
	1,  // 14: accelbyte.challenge.assignmentFunction.AssignmentFunction.Assign:input_type -> accelbyte.challenge.assignmentFunction.AssignmentRequest
	2,  // 15: accelbyte.challenge.assignmentFunction.AssignmentFunction.Assign:output_type -> accelbyte.challenge.assignmentFunction.AssignmentResponse
	15, // [15:16] is the sub-list for method output_type
	14, // [14:15] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_assignment_function_proto_init() }
func file_assignment_function_proto_init() {
	if File_assignment_function_proto != nil {
		return
	}
	file_assignment_function_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_assignment_function_proto_rawDesc), len(file_assignment_function_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_assignment_function_proto_goTypes,
		DependencyIndexes: file_assignment_function_proto_depIdxs,
		EnumInfos:         file_assignment_function_proto_enumTypes,
		MessageInfos:      file_assignment_function_proto_msgTypes,
	}.Build()
	File_assignment_function_proto = out.File
	file_assignment_function_proto_goTypes = nil
	file_assignment_function_proto_depIdxs = nil
}
