// Copyright (c) 2024 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.9
// source: assignment_function.proto

package assignmentFunction

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AssignmentFunction_Assign_FullMethodName = "/accelbyte.challenge.assignmentFunction.AssignmentFunction/Assign"
)

// AssignmentFunctionClient is the client API for AssignmentFunction service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AssignmentFunctionClient interface {
	Assign(ctx context.Context, in *AssignmentRequest, opts ...grpc.CallOption) (*AssignmentResponse, error)
}

type assignmentFunctionClient struct {
	cc grpc.ClientConnInterface
}

func NewAssignmentFunctionClient(cc grpc.ClientConnInterface) AssignmentFunctionClient {
	return &assignmentFunctionClient{cc}
}

func (c *assignmentFunctionClient) Assign(ctx context.Context, in *AssignmentRequest, opts ...grpc.CallOption) (*AssignmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssignmentResponse)
	err := c.cc.Invoke(ctx, AssignmentFunction_Assign_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AssignmentFunctionServer is the server API for AssignmentFunction service.
// All implementations should embed UnimplementedAssignmentFunctionServer
// for forward compatibility.
type AssignmentFunctionServer interface {
	Assign(context.Context, *AssignmentRequest) (*AssignmentResponse, error)
}

// UnimplementedAssignmentFunctionServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAssignmentFunctionServer struct{}

func (UnimplementedAssignmentFunctionServer) Assign(context.Context, *AssignmentRequest) (*AssignmentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Assign not implemented")
}
func (UnimplementedAssignmentFunctionServer) testEmbeddedByValue() {}

// UnsafeAssignmentFunctionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AssignmentFunctionServer will
// result in compilation errors.
type UnsafeAssignmentFunctionServer interface {
	mustEmbedUnimplementedAssignmentFunctionServer()
}

func RegisterAssignmentFunctionServer(s grpc.ServiceRegistrar, srv AssignmentFunctionServer) {
	// If the following call panics, it indicates UnimplementedAssignmentFunctionServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AssignmentFunction_ServiceDesc, srv)
}

func _AssignmentFunction_Assign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssignmentFunctionServer).Assign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssignmentFunction_Assign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssignmentFunctionServer).Assign(ctx, req.(*AssignmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AssignmentFunction_ServiceDesc is the grpc.ServiceDesc for AssignmentFunction service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AssignmentFunction_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "accelbyte.challenge.assignmentFunction.AssignmentFunction",
	HandlerType: (*AssignmentFunctionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Assign",
			Handler:    _AssignmentFunction_Assign_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "assignment_function.proto",
}
